# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "lab6" ]
  pull_request:
    branches: [ "lab6" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: build with maven
      run: mvn -B package --file pom.xml
    - name: set ssh key
      run: |
        mkdir -p ~/.ssh/
        echo "${{secrets.COSEN_ID_RSA}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan "43.142.159.174" >> ~/.ssh/known_hosts      
    - name: scp
      run: scp target/ERP-0.0.1-SNAPSHOT.jar ubuntu@43.142.159.174:~/erp/back-end
    - name: deploy
      run: |
        ssh ubuntu@43.142.159.174 "
          ./backend-setup.sh
        "
    - name: delete ssh key
      run: rm -rf ~/.ssh/id_rsa
